"""Curated Yoga / Movement Exercise Library for AYURAGIES.

Every exercise is a structured data entry with indication / contraindication
fields -- NOT inline text.  The list is intentionally conservative and uses
only exercises suitable for adults with lower-extremity joint concerns.
"""
from __future__ import annotations

from .models import EvidenceType, ExerciseCategory, YogaExercise

EXERCISE_LIBRARY: list[YogaExercise] = [
    # ─────────────────── WARM-UP ───────────────────
    YogaExercise(
        id="WU-01",
        name="Ankle Circles",
        sanskrit_name=None,
        category=ExerciseCategory.WARM_UP,
        target_areas=["ankle", "foot", "calf"],
        difficulty="Beginner",
        recommended_duration="2\u20133 minutes",
        recommended_repetitions="10 circles each direction per foot",
        recommended_frequency="Daily or before exercise",
        instructions=[
            "Sit on a stable chair with feet on the floor.",
            "Lift one foot slightly off the ground.",
            "Slowly rotate the ankle in a full circle, 10 times clockwise.",
            "Repeat 10 times counter-clockwise.",
            "Switch to the other foot.",
        ],
        expected_purpose="Improve ankle mobility and warm up lower-extremity joints before movement.",
        precautions=["Avoid if acute ankle injury is present.", "Reduce range if pain occurs."],
        stop_conditions=["Sharp pain in the ankle.", "Increased swelling in the foot."],
        indications=["stiffness", "sedentary lifestyle", "pre-exercise warm-up"],
        contraindications=["acute ankle fracture", "severe ankle instability"],
        camera_tracking_available=False,
        tracking_metric=None,
        required_equipment=["Stable chair"],
        evidence_type=EvidenceType.REHABILITATION,
    ),
    YogaExercise(
        id="WU-02",
        name="Marching in Place",
        sanskrit_name=None,
        category=ExerciseCategory.WARM_UP,
        target_areas=["hip flexors", "quadriceps", "cardiovascular"],
        difficulty="Beginner",
        recommended_duration="2\u20133 minutes",
        recommended_repetitions="20\u201330 steps",
        recommended_frequency="Daily or before exercise",
        instructions=[
            "Stand near a chair or wall for support if needed.",
            "Lift one knee to a comfortable height (approximately hip level).",
            "Lower it slowly and repeat with the other leg.",
            "Maintain an upright trunk throughout.",
            "Use a controlled, rhythmic tempo.",
        ],
        expected_purpose="Gently raise heart rate and prepare lower-limb muscles for activity.",
        precautions=["Use support if balance is limited.", "Reduce knee lift height if hip or knee pain occurs."],
        stop_conditions=["Knee pain increases above baseline.", "Dizziness or loss of balance."],
        indications=["low activity level", "pre-exercise warm-up"],
        contraindications=["acute hip injury", "severe balance impairment without support"],
        camera_tracking_available=True,
        tracking_metric="knee_raise_height",
        required_equipment=[],
        evidence_type=EvidenceType.GENERAL_HEALTH,
    ),

    # ─────────────────── MOBILITY ───────────────────
    YogaExercise(
        id="MOB-01",
        name="Chair-Supported Knee Flexion",
        sanskrit_name=None,
        category=ExerciseCategory.MOBILITY,
        target_areas=["knee", "quadriceps", "hamstrings"],
        difficulty="Beginner",
        recommended_duration="5\u201310 minutes",
        recommended_repetitions="8\u201312 per leg",
        recommended_frequency="3\u20135 sessions per week",
        instructions=[
            "Stand behind a stable chair, hands resting on the backrest.",
            "Slowly bend one knee, bringing the heel toward the buttock.",
            "Hold at a comfortable end-range for 2\u20133 seconds.",
            "Lower the foot slowly back to the floor.",
            "Repeat on the other leg.",
        ],
        expected_purpose="Maintain or improve knee flexion range of motion through gentle active movement.",
        precautions=["Use chair support to maintain balance.", "Do not force knee flexion beyond comfort.", "Avoid on unstable surfaces."],
        stop_conditions=["Sharp knee pain.", "Significant swelling after the session."],
        indications=["reduced knee flexion ROM", "stiffness", "moderate pain level"],
        contraindications=["acute knee injury", "post-operative state (until cleared)", "severe instability"],
        camera_tracking_available=True,
        tracking_metric="knee_flexion_angle",
        required_equipment=["Stable chair"],
        evidence_type=EvidenceType.REHABILITATION,
    ),
    YogaExercise(
        id="MOB-02",
        name="Seated Knee Extension",
        sanskrit_name=None,
        category=ExerciseCategory.MOBILITY,
        target_areas=["knee", "quadriceps"],
        difficulty="Beginner",
        recommended_duration="5\u20138 minutes",
        recommended_repetitions="10\u201315 per leg",
        recommended_frequency="3\u20135 sessions per week",
        instructions=[
            "Sit on a chair with back supported and feet flat on the floor.",
            "Slowly straighten one leg until it is parallel to the floor.",
            "Hold for 3\u20135 seconds.",
            "Lower the foot slowly.",
            "Repeat on the other side.",
        ],
        expected_purpose="Strengthen the quadriceps and improve knee extension without high joint loading.",
        precautions=["Keep movement slow and controlled.", "Stop if locking or catching sensation is felt."],
        stop_conditions=["Sharp anterior knee pain.", "Clicking associated with pain."],
        indications=["quad weakness", "reduced knee extension", "post-activity stiffness"],
        contraindications=["acute patellar injury", "severe effusion"],
        camera_tracking_available=True,
        tracking_metric="knee_extension_angle",
        required_equipment=["Chair with backrest"],
        evidence_type=EvidenceType.REHABILITATION,
    ),
    YogaExercise(
        id="MOB-03",
        name="Heel Slides (Supine Knee Flexion)",
        sanskrit_name=None,
        category=ExerciseCategory.MOBILITY,
        target_areas=["knee", "hip"],
        difficulty="Beginner",
        recommended_duration="5 minutes",
        recommended_repetitions="10 per leg",
        recommended_frequency="Daily or 5 sessions per week",
        instructions=[
            "Lie on your back on a firm surface (mat or bed).",
            "Slowly slide one heel toward your buttock, bending the knee.",
            "Slide as far as comfortable, then slowly straighten.",
            "Keep the foot in contact with the surface throughout.",
        ],
        expected_purpose="Improve knee flexion with minimal weight-bearing stress.",
        precautions=["Use a smooth surface to reduce friction."],
        stop_conditions=["Knee pain beyond baseline.", "Inability to slide the heel smoothly."],
        indications=["post-operative rehabilitation (when cleared)", "severe stiffness", "high pain limiting standing exercises"],
        contraindications=["active wound at knee", "unstable fracture"],
        camera_tracking_available=False,
        tracking_metric=None,
        required_equipment=["Mat or firm bed"],
        evidence_type=EvidenceType.REHABILITATION,
    ),

    # ─────────────────── STRENGTH ───────────────────
    YogaExercise(
        id="STR-01",
        name="Sit-to-Stand",
        sanskrit_name=None,
        category=ExerciseCategory.STRENGTH,
        target_areas=["quadriceps", "glutes", "core"],
        difficulty="Beginner",
        recommended_duration="5 minutes",
        recommended_repetitions="5\u201310",
        recommended_frequency="3\u20134 sessions per week",
        instructions=[
            "Sit on a stable chair with feet flat on the floor, shoulder-width apart.",
            "Lean slightly forward at the hips.",
            "Press through your heels to stand up.",
            "Pause at the top for 1\u20132 seconds.",
            "Slowly lower back to a seated position.",
            "Use armrests or a walker for support if needed.",
        ],
        expected_purpose="Build lower-limb functional strength used in daily activities.",
        precautions=["Use arm support if needed.", "Ensure the chair is stable and will not slide."],
        stop_conditions=["Knee gives way.", "Sharp pain during standing phase."],
        indications=["functional weakness", "difficulty rising from seated position"],
        contraindications=["acute knee injury", "severe instability", "uncontrolled balance disorder"],
        camera_tracking_available=True,
        tracking_metric="sit_to_stand_knee_angle",
        required_equipment=["Stable chair"],
        evidence_type=EvidenceType.REHABILITATION,
    ),
    YogaExercise(
        id="STR-02",
        name="Wall Mini-Squat",
        sanskrit_name=None,
        category=ExerciseCategory.STRENGTH,
        target_areas=["quadriceps", "glutes", "hip"],
        difficulty="Beginner",
        recommended_duration="5 minutes",
        recommended_repetitions="8\u201312",
        recommended_frequency="3 sessions per week",
        instructions=[
            "Stand with your back flat against a smooth wall.",
            "Place feet about 30 cm from the wall, shoulder-width apart.",
            "Slowly slide down the wall to a comfortable depth (quarter-squat).",
            "Hold for 3\u20135 seconds.",
            "Slowly slide back up.",
        ],
        expected_purpose="Strengthen lower-limb muscles with wall support to reduce joint loading.",
        precautions=["Do not squat below 90\u00b0 knee angle.", "Keep knees aligned over the second toe."],
        stop_conditions=["Knee pain increases.", "Inability to push back up."],
        indications=["quad weakness", "moderate knee flexion tolerance"],
        contraindications=["acute swelling", "severe knee instability", "post-operative (until cleared)"],
        camera_tracking_available=True,
        tracking_metric="squat_knee_angle",
        required_equipment=["Smooth wall"],
        evidence_type=EvidenceType.REHABILITATION,
    ),
    YogaExercise(
        id="STR-03",
        name="Isometric Quadriceps Set",
        sanskrit_name=None,
        category=ExerciseCategory.STRENGTH,
        target_areas=["quadriceps"],
        difficulty="Beginner",
        recommended_duration="5 minutes",
        recommended_repetitions="10 holds of 5\u201310 seconds each",
        recommended_frequency="Daily",
        instructions=[
            "Sit or lie down with the leg extended.",
            "Tighten the thigh muscle by pressing the back of the knee flat.",
            "Hold for 5\u201310 seconds.",
            "Relax and repeat.",
        ],
        expected_purpose="Activate and strengthen quadriceps without joint movement, suitable for painful or swollen knees.",
        precautions=["Maintain normal breathing; do not hold breath."],
        stop_conditions=["Increased pain under the kneecap."],
        indications=["acute swelling", "high pain", "post-operative", "severe stiffness"],
        contraindications=[],
        camera_tracking_available=False,
        tracking_metric=None,
        required_equipment=[],
        evidence_type=EvidenceType.REHABILITATION,
    ),

    # ─────────────────── BALANCE ───────────────────
    YogaExercise(
        id="BAL-01",
        name="Tandem Stance",
        sanskrit_name=None,
        category=ExerciseCategory.BALANCE,
        target_areas=["ankle", "knee", "core", "proprioception"],
        difficulty="Beginner",
        recommended_duration="3\u20135 minutes",
        recommended_repetitions="Hold 15\u201330 seconds, 3\u20134 sets",
        recommended_frequency="3\u20135 sessions per week",
        instructions=[
            "Stand near a counter or wall for safety.",
            "Place one foot directly in front of the other (heel-to-toe).",
            "Hold the position for 15\u201330 seconds.",
            "Switch leading foot and repeat.",
        ],
        expected_purpose="Improve static balance and proprioception relevant to fall prevention.",
        precautions=["Stay within arm\u2019s reach of a support surface."],
        stop_conditions=["Significant unsteadiness.", "Pain."],
        indications=["balance deficit", "fall history", "low activity level"],
        contraindications=["severe vertigo", "lower-limb fracture"],
        camera_tracking_available=False,
        tracking_metric=None,
        required_equipment=[],
        evidence_type=EvidenceType.REHABILITATION,
    ),
    YogaExercise(
        id="BAL-02",
        name="Single Leg Stance (Supported)",
        sanskrit_name=None,
        category=ExerciseCategory.BALANCE,
        target_areas=["hip", "ankle", "core"],
        difficulty="Intermediate",
        recommended_duration="3\u20135 minutes",
        recommended_repetitions="Hold 10\u201320 seconds each side, 3 sets",
        recommended_frequency="3\u20135 sessions per week",
        instructions=[
            "Stand next to a stable support surface.",
            "Lift one foot slightly off the ground.",
            "Hold the position for 10\u201320 seconds.",
            "Lower the foot and switch sides.",
        ],
        expected_purpose="Challenge balance on a single limb to build ankle and hip stability.",
        precautions=["Keep hand near support surface.", "Avoid if severe knee instability."],
        stop_conditions=["Loss of balance.", "Knee or hip pain."],
        indications=["moderate balance deficit", "gait asymmetry"],
        contraindications=["severe knee instability", "acute injury"],
        camera_tracking_available=True,
        tracking_metric="single_leg_stance_time",
        required_equipment=[],
        evidence_type=EvidenceType.REHABILITATION,
    ),

    # ─────────────────── YOGA (Classical) ───────────────────
    YogaExercise(
        id="YOGA-01",
        name="Chair Pose (Modified)",
        sanskrit_name="Utkatasana (Modified)",
        category=ExerciseCategory.YOGA,
        target_areas=["quadriceps", "glutes", "core", "ankle"],
        difficulty="Beginner",
        recommended_duration="5 minutes",
        recommended_repetitions="3\u20135 holds of 10\u201315 seconds",
        recommended_frequency="3\u20144 sessions per week",
        instructions=[
            "Stand with feet hip-width apart.",
            "Extend arms forward or bring palms together at chest level.",
            "Slowly bend knees to a comfortable depth (partial squat).",
            "Keep the trunk upright; do not let knees go past toes.",
            "Hold for 10\u201315 seconds, breathing steadily.",
            "Slowly return to standing.",
        ],
        expected_purpose="Strengthen lower limbs using a familiar yoga posture adapted for reduced knee tolerance.",
        precautions=["Keep squat depth shallow to avoid excessive knee loading.", "Use a wall behind you for confidence if needed."],
        stop_conditions=["Knee pain during the hold.", "Loss of balance."],
        indications=["moderate knee flexion tolerance", "functional weakness"],
        contraindications=["acute swelling", "high pain level (>7/10)", "severe instability"],
        camera_tracking_available=True,
        tracking_metric="squat_knee_angle",
        required_equipment=[],
        evidence_type=EvidenceType.GENERAL_HEALTH,
    ),
    YogaExercise(
        id="YOGA-02",
        name="Tree Pose (Modified)",
        sanskrit_name="Vrksasana (Modified)",
        category=ExerciseCategory.YOGA,
        target_areas=["hip", "ankle", "core", "balance"],
        difficulty="Intermediate",
        recommended_duration="3\u20135 minutes",
        recommended_repetitions="3 holds of 15\u201330 seconds each side",
        recommended_frequency="3\u20144 sessions per week",
        instructions=[
            "Stand near a wall or chair for support.",
            "Place one foot against the inner ankle or calf (not directly on the knee).",
            "Bring palms together at chest level or rest one hand on the wall.",
            "Hold for 15\u201330 seconds, then switch sides.",
        ],
        expected_purpose="Improve single-leg balance and hip stability through a gentle yoga posture.",
        precautions=["Do not press foot against the standing knee.", "Keep a support surface nearby."],
        stop_conditions=["Knee pain in the standing leg.", "Persistent loss of balance."],
        indications=["balance deficit", "hip weakness"],
        contraindications=["severe knee instability", "acute injury", "severe balance impairment"],
        camera_tracking_available=False,
        tracking_metric=None,
        required_equipment=[],
        evidence_type=EvidenceType.GENERAL_HEALTH,
    ),
    YogaExercise(
        id="YOGA-03",
        name="Seated Spinal Twist",
        sanskrit_name="Ardha Matsyendrasana (Seated Variation)",
        category=ExerciseCategory.YOGA,
        target_areas=["spine", "hip", "obliques"],
        difficulty="Beginner",
        recommended_duration="5 minutes",
        recommended_repetitions="3\u20145 holds of 15\u201320 seconds each side",
        recommended_frequency="3\u20145 sessions per week",
        instructions=[
            "Sit on a chair with feet flat on the floor.",
            "Place one hand on the outside of the opposite knee.",
            "Gently twist the upper body toward that side.",
            "Hold for 15\u201320 seconds, breathing normally.",
            "Return to center and repeat on the other side.",
        ],
        expected_purpose="Maintain spinal mobility and gentle trunk rotation.",
        precautions=["Twist gently; do not force rotation.", "Avoid if recent spinal surgery."],
        stop_conditions=["Back pain or radiating symptoms."],
        indications=["spinal stiffness", "sedentary lifestyle", "upper body tension"],
        contraindications=["acute spinal injury", "disc herniation"],
        camera_tracking_available=False,
        tracking_metric=None,
        required_equipment=["Chair"],
        evidence_type=EvidenceType.GENERAL_HEALTH,
    ),
    YogaExercise(
        id="YOGA-04",
        name="Supine Bound Angle Pose",
        sanskrit_name="Supta Baddha Konasana",
        category=ExerciseCategory.YOGA,
        target_areas=["hip", "inner thigh", "pelvic floor"],
        difficulty="Beginner",
        recommended_duration="3\u20145 minutes",
        recommended_repetitions="1\u20132 holds of 60\u201390 seconds",
        recommended_frequency="3\u20145 sessions per week",
        instructions=[
            "Lie on your back.",
            "Bring the soles of the feet together and let the knees fall outward.",
            "Support the outer thighs with cushions or folded towels.",
            "Rest hands on the abdomen or by your sides.",
            "Breathe slowly and hold.",
        ],
        expected_purpose="Gently open the hips and inner thighs in a restorative, supported position.",
        precautions=["Use bolsters or cushions under the knees.", "Avoid forcing knees toward the floor."],
        stop_conditions=["Groin pain.", "Inner knee discomfort."],
        indications=["hip stiffness", "stress", "sedentary lifestyle"],
        contraindications=["acute groin injury", "sacroiliac joint instability"],
        camera_tracking_available=False,
        tracking_metric=None,
        required_equipment=["Mat", "Cushion or bolster"],
        evidence_type=EvidenceType.GENERAL_HEALTH,
    ),

    # ─────────────────── STRETCHING ───────────────────
    YogaExercise(
        id="STR-04",
        name="Standing Quadriceps Stretch",
        sanskrit_name=None,
        category=ExerciseCategory.STRETCHING,
        target_areas=["quadriceps", "hip flexors"],
        difficulty="Beginner",
        recommended_duration="3\u20145 minutes",
        recommended_repetitions="3 holds of 20\u201330 seconds each side",
        recommended_frequency="Daily or after exercise",
        instructions=[
            "Stand next to a wall or chair for support.",
            "Bend one knee and bring the heel toward the buttock.",
            "Hold the ankle (use a strap if needed) and keep the knees together.",
            "Hold for 20\u201330 seconds.",
            "Switch sides.",
        ],
        expected_purpose="Maintain quadriceps flexibility and reduce anterior knee tightness.",
        precautions=["Avoid if acute anterior knee pain.", "Do not pull aggressively."],
        stop_conditions=["Sharp knee pain.", "Cramping in the thigh."],
        indications=["post-exercise cooldown", "quadriceps tightness"],
        contraindications=["acute patellar tendon injury", "severe knee effusion"],
        camera_tracking_available=True,
        tracking_metric="knee_flexion_angle",
        required_equipment=[],
        evidence_type=EvidenceType.GENERAL_HEALTH,
    ),
    YogaExercise(
        id="STR-05",
        name="Seated Hamstring Stretch",
        sanskrit_name=None,
        category=ExerciseCategory.STRETCHING,
        target_areas=["hamstrings", "lower back"],
        difficulty="Beginner",
        recommended_duration="3\u20145 minutes",
        recommended_repetitions="3 holds of 20\u201330 seconds each side",
        recommended_frequency="Daily or after exercise",
        instructions=[
            "Sit on the edge of a chair.",
            "Extend one leg forward with heel on the floor and toes pointing up.",
            "Keeping the back straight, gently lean forward from the hips.",
            "Hold when a gentle stretch is felt behind the thigh.",
            "Switch sides.",
        ],
        expected_purpose="Maintain hamstring flexibility, which supports knee and hip mechanics.",
        precautions=["Keep back straight; do not round the spine.", "Avoid bouncing."],
        stop_conditions=["Pain behind the knee.", "Numbness or tingling."],
        indications=["hamstring tightness", "limited forward bend", "post-activity"],
        contraindications=["acute posterior thigh injury", "sciatica in acute phase"],
        camera_tracking_available=False,
        tracking_metric=None,
        required_equipment=["Chair"],
        evidence_type=EvidenceType.GENERAL_HEALTH,
    ),
    YogaExercise(
        id="STR-06",
        name="Calf Stretch (Wall Lean)",
        sanskrit_name=None,
        category=ExerciseCategory.STRETCHING,
        target_areas=["calf", "achilles tendon", "ankle"],
        difficulty="Beginner",
        recommended_duration="3 minutes",
        recommended_repetitions="3 holds of 20\u201330 seconds each side",
        recommended_frequency="Daily",
        instructions=[
            "Stand facing a wall with hands placed on it at shoulder height.",
            "Step one foot back, keeping the heel on the ground.",
            "Lean into the wall until a stretch is felt in the back calf.",
            "Hold for 20\u201330 seconds.",
            "Switch sides.",
        ],
        expected_purpose="Maintain calf and achilles flexibility important for gait mechanics.",
        precautions=["Do not bounce.", "Keep the back heel grounded."],
        stop_conditions=["Achilles tendon pain.", "Calf cramping."],
        indications=["calf tightness", "limited ankle dorsiflexion", "gait pattern abnormality"],
        contraindications=["acute achilles tendon injury", "calf strain"],
        camera_tracking_available=False,
        tracking_metric=None,
        required_equipment=["Wall"],
        evidence_type=EvidenceType.GENERAL_HEALTH,
    ),
]


def get_exercise_by_id(exercise_id: str) -> YogaExercise | None:
    """Retrieve a single exercise by its unique ID."""
    for ex in EXERCISE_LIBRARY:
        if ex.id == exercise_id:
            return ex
    return None


def get_exercises_by_category(category: ExerciseCategory) -> list[YogaExercise]:
    """Return all exercises of a given category."""
    return [ex for ex in EXERCISE_LIBRARY if ex.category == category]


def get_exercises_by_difficulty(difficulty: str) -> list[YogaExercise]:
    return [ex for ex in EXERCISE_LIBRARY if ex.difficulty == difficulty]


def get_camera_trackable_exercises() -> list[YogaExercise]:
    return [ex for ex in EXERCISE_LIBRARY if ex.camera_tracking_available]
